import type { FeatureModuleDefinition } from "@/features/types"

export const marketplaceFeatureModule = {
  key: "marketplace",
  flagName: "marketplace_access",
  name: "Marketplace",
  description: "B2B marketplace module with listings, matching, contracts, disputes, and compliance flows.",
  defaultEnabled: false,
  ownedPaths: [
    "features/marketplace",
    "app/[locale]/(authenticated)/marketplace",
    "app/[locale]/(legal)/marketplace-terms",
    "app/[locale]/(legal)/p2b-complaint",
    "app/api/marketplace",
    "app/api/matching-engine",
    "app/api/dac7",
    "app/api/webhooks/stripe-connect",
    "actions/marketplace",
    "components/marketplace",
    "lib/marketplace",
    "supabase/migrations/20260210000100_marketplace_profiles.sql",
    "supabase/migrations/20260210000200_service_listings.sql",
    "supabase/migrations/20260210000300_order_matches.sql",
    "supabase/migrations/20260210000400_contracts.sql",
    "supabase/migrations/20260210000500_disputes.sql",
    "supabase/migrations/20260210000600_compliance_tables.sql",
    "supabase/migrations/20260210000700_marketplace_triggers.sql",
    "supabase/migrations/20260210000800_marketplace_feature_flag.sql",
    "supabase/migrations/20260210000900_listing_price_range.sql",
  ],
  routePrefixes: [
    "/marketplace",
    "/marketplace-terms",
    "/p2b-complaint",
    "/api/marketplace",
    "/api/matching-engine",
    "/api/dac7",
    "/api/webhooks/stripe-connect",
  ],
} satisfies FeatureModuleDefinition
